version: '2'
services:
    road-app:
        image: road
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://road-postgresql:5432/road
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    road-postgresql:
        extends:
            file: postgresql.yml
            service: road-postgresql
